#' Run the Shiny Application
#' Start the Shiny based interactive visualization tool to show the subgroup
#' results generated by subscreencalc.
#' See and explore all subgroup results at one glance. Pick and chose a specific
#' subgroup, the level of combinations or a certain factor with its
#' combinations. Switch easily between different endpoint/target variables.
#'
#' @param scresults SubScreenResult object with results from a subscreencalc
#' call
#' @param variable_importance variable importance object calculated via
#' subscreenvi to unlock 'variable importance'-tab in the app
#' @param nice_numbers list of numbers used for a 'nice' scale
#' @param graphSubtitle subtitle for explorer plot
#' @param favour_label_verum_name verum name for label use in explorer graph
#' @param favour_label_comparator_name comparator name for label use in explorer
#' graph
#' @param showTables logical for display tables in 'Explorer tab'
#' @param reference_line_at_start logical for reference line appearance at
#' start (TRUE/FALSE)
#' @param reference_value numeric value of horizontal reference line
#' @param favour_label_at_start logical for favour labels appearance at start
#' (TRUE/FALSE)
#' @param favour_direction logical for favor label direction (TRUE/FALSE) where
#' TRUE means favour_label_verum_name is on top
#' @param subgroup_levels_at_start integer value for subgroup level slider at
#' start
#' @param yaxis_type character ("lin"/"log") for yaxis type
#' @param add_funnel_at_start logical for funnel appearance at start
#' (TRUE/FALSE)
#'
#' @keywords subgroup analysis visualization
#' @param ... arguments to pass to golem_opts.
#' See `?golem::get_golem_options` for more details.
#' @inheritParams shiny::shinyApp
#'
#' @export
run_app <- function(
  onStart = NULL,
  options = list(),
  enableBookmarking = NULL,
  uiPattern = "/",
  scresults = NULL,
  variable_importance = NULL,
  nice_numbers = c(1, 1.5, 2, 4, 5, 6, 8, 10),
  graphSubtitle = NULL,
  favour_label_verum_name = NULL,
  favour_label_comparator_name = NULL,
  showTables = FALSE,
  reference_line_at_start = FALSE,
  reference_value = 1,
  favour_label_at_start = FALSE,
  favour_direction = TRUE,
  subgroup_levels_at_start = NA,
  yaxis_type = "lin",
  add_funnel_at_start = FALSE,
  ...
) {
  golem::with_golem_options(
    app = shiny::shinyApp(
      ui = app_ui,
      server = app_server,
      onStart = onStart,
      options = options,
      enableBookmarking = enableBookmarking,
      uiPattern = uiPattern
    ),
    golem_opts = list(
      scresults = scresults,
      variable_importance = variable_importance,
      nice_numbers = nice_numbers,
      graphSubtitle = graphSubtitle,
      favour_label_verum_name = favour_label_verum_name,
      favour_label_comparator_name = favour_label_comparator_name,
      showTables = showTables,
      reference_line_at_start = reference_line_at_start,
      reference_value = reference_value,
      favour_label_at_start = favour_label_at_start,
      favour_direction = favour_direction,
      subgroup_levels_at_start = subgroup_levels_at_start,
      yaxis_type = yaxis_type,
      add_funnel_at_start = add_funnel_at_start,
      ...
    )
  )
}
